// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: proto/summarizer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for summarizing prepared messages
type SummarizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of messages to summarize
	Messages      []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_proto_summarizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summarizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_summarizer_proto_rawDescGZIP(), []int{0}
}

func (x *SummarizeRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Request for summarizing Matrix room
type SummarizeMatrixRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matrix user credentials (required)
	MatrixUsername string `protobuf:"bytes,1,opt,name=matrix_username,json=matrixUsername,proto3" json:"matrix_username,omitempty"` // user@example.com
	MatrixPassword string `protobuf:"bytes,2,opt,name=matrix_password,json=matrixPassword,proto3" json:"matrix_password,omitempty"` // password123
	// Matrix server (one of two is required)
	MatrixHomeserverUrl string `protobuf:"bytes,3,opt,name=matrix_homeserver_url,json=matrixHomeserverUrl,proto3" json:"matrix_homeserver_url,omitempty"` // https://matrix.example.com (optional)
	MatrixServername    string `protobuf:"bytes,4,opt,name=matrix_servername,json=matrixServername,proto3" json:"matrix_servername,omitempty"`            // example.com (optional, used if homeserver_url not specified)
	// Chat parameters (one of two is required)
	RoomId    string `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`          // !room123:example.com (optional)
	RoomAlias string `protobuf:"bytes,6,opt,name=room_alias,json=roomAlias,proto3" json:"room_alias,omitempty"` // #general:example.com (optional)
	// Additional parameters
	MessageCount  int32 `protobuf:"varint,7,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"` // 50 (default 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeMatrixRoomRequest) Reset() {
	*x = SummarizeMatrixRoomRequest{}
	mi := &file_proto_summarizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeMatrixRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeMatrixRoomRequest) ProtoMessage() {}

func (x *SummarizeMatrixRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summarizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeMatrixRoomRequest.ProtoReflect.Descriptor instead.
func (*SummarizeMatrixRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_summarizer_proto_rawDescGZIP(), []int{1}
}

func (x *SummarizeMatrixRoomRequest) GetMatrixUsername() string {
	if x != nil {
		return x.MatrixUsername
	}
	return ""
}

func (x *SummarizeMatrixRoomRequest) GetMatrixPassword() string {
	if x != nil {
		return x.MatrixPassword
	}
	return ""
}

func (x *SummarizeMatrixRoomRequest) GetMatrixHomeserverUrl() string {
	if x != nil {
		return x.MatrixHomeserverUrl
	}
	return ""
}

func (x *SummarizeMatrixRoomRequest) GetMatrixServername() string {
	if x != nil {
		return x.MatrixServername
	}
	return ""
}

func (x *SummarizeMatrixRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SummarizeMatrixRoomRequest) GetRoomAlias() string {
	if x != nil {
		return x.RoomAlias
	}
	return ""
}

func (x *SummarizeMatrixRoomRequest) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

// Chat message
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message author
	Author string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	// Message content
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Send time (timestamp)
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Message type (text, image, file, etc.)
	MessageType   string `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_summarizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summarizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_summarizer_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

// Summarization response
type SummarizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Summarization result
	Summary string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	// Number of processed messages
	MessageCount int32 `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	// Processing status
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Additional information
	Metadata      string `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeResponse) Reset() {
	*x = SummarizeResponse{}
	mi := &file_proto_summarizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeResponse) ProtoMessage() {}

func (x *SummarizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summarizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeResponse.ProtoReflect.Descriptor instead.
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_summarizer_proto_rawDescGZIP(), []int{3}
}

func (x *SummarizeResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummarizeResponse) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SummarizeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SummarizeResponse) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// Matrix room summarization response
type SummarizeMatrixRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Summarization result
	Summary       string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeMatrixRoomResponse) Reset() {
	*x = SummarizeMatrixRoomResponse{}
	mi := &file_proto_summarizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeMatrixRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeMatrixRoomResponse) ProtoMessage() {}

func (x *SummarizeMatrixRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_summarizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeMatrixRoomResponse.ProtoReflect.Descriptor instead.
func (*SummarizeMatrixRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_summarizer_proto_rawDescGZIP(), []int{4}
}

func (x *SummarizeMatrixRoomResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_proto_summarizer_proto protoreflect.FileDescriptor

const file_proto_summarizer_proto_rawDesc = "" +
	"\n" +
	"\x16proto/summarizer.proto\x12\n" +
	"summarizer\"C\n" +
	"\x10SummarizeRequest\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.summarizer.MessageR\bmessages\"\xac\x02\n" +
	"\x1aSummarizeMatrixRoomRequest\x12'\n" +
	"\x0fmatrix_username\x18\x01 \x01(\tR\x0ematrixUsername\x12'\n" +
	"\x0fmatrix_password\x18\x02 \x01(\tR\x0ematrixPassword\x122\n" +
	"\x15matrix_homeserver_url\x18\x03 \x01(\tR\x13matrixHomeserverUrl\x12+\n" +
	"\x11matrix_servername\x18\x04 \x01(\tR\x10matrixServername\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"room_alias\x18\x06 \x01(\tR\troomAlias\x12#\n" +
	"\rmessage_count\x18\a \x01(\x05R\fmessageCount\"|\n" +
	"\aMessage\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\"\x86\x01\n" +
	"\x11SummarizeResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x05R\fmessageCount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"7\n" +
	"\x1bSummarizeMatrixRoomResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary2\xc5\x01\n" +
	"\x11SummarizerService\x12H\n" +
	"\tSummarize\x12\x1c.summarizer.SummarizeRequest\x1a\x1d.summarizer.SummarizeResponse\x12f\n" +
	"\x13SummarizeMatrixRoom\x12&.summarizer.SummarizeMatrixRoomRequest\x1a'.summarizer.SummarizeMatrixRoomResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_summarizer_proto_rawDescOnce sync.Once
	file_proto_summarizer_proto_rawDescData []byte
)

func file_proto_summarizer_proto_rawDescGZIP() []byte {
	file_proto_summarizer_proto_rawDescOnce.Do(func() {
		file_proto_summarizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_summarizer_proto_rawDesc), len(file_proto_summarizer_proto_rawDesc)))
	})
	return file_proto_summarizer_proto_rawDescData
}

var file_proto_summarizer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_summarizer_proto_goTypes = []any{
	(*SummarizeRequest)(nil),            // 0: summarizer.SummarizeRequest
	(*SummarizeMatrixRoomRequest)(nil),  // 1: summarizer.SummarizeMatrixRoomRequest
	(*Message)(nil),                     // 2: summarizer.Message
	(*SummarizeResponse)(nil),           // 3: summarizer.SummarizeResponse
	(*SummarizeMatrixRoomResponse)(nil), // 4: summarizer.SummarizeMatrixRoomResponse
}
var file_proto_summarizer_proto_depIdxs = []int32{
	2, // 0: summarizer.SummarizeRequest.messages:type_name -> summarizer.Message
	0, // 1: summarizer.SummarizerService.Summarize:input_type -> summarizer.SummarizeRequest
	1, // 2: summarizer.SummarizerService.SummarizeMatrixRoom:input_type -> summarizer.SummarizeMatrixRoomRequest
	3, // 3: summarizer.SummarizerService.Summarize:output_type -> summarizer.SummarizeResponse
	4, // 4: summarizer.SummarizerService.SummarizeMatrixRoom:output_type -> summarizer.SummarizeMatrixRoomResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_summarizer_proto_init() }
func file_proto_summarizer_proto_init() {
	if File_proto_summarizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_summarizer_proto_rawDesc), len(file_proto_summarizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_summarizer_proto_goTypes,
		DependencyIndexes: file_proto_summarizer_proto_depIdxs,
		MessageInfos:      file_proto_summarizer_proto_msgTypes,
	}.Build()
	File_proto_summarizer_proto = out.File
	file_proto_summarizer_proto_goTypes = nil
	file_proto_summarizer_proto_depIdxs = nil
}
